# Configuración del plugin NiiniiwiPerma
mechanics:
    # Prevenir la minería de Ancient Debris (true = sí, false = no)
    can_player_mine_ancient_debris: true

messages:
    ancient_debris_denied: "<#a11316>[✖] <#787878>No puedes minar <#ff8d0a>Ancient Debris."
    reload_success: "<green>[✔] <#787878>Configuracion Recargada."
    mineancient_enabled: "<green>[✔] <#787878><green>Habilitado</green> el Minar <#ff8d0a>Ancient Debris.<reset>"
    mineancient_disabled: "<#a11316>[✖] <#787878><red>Deshabilitado</red> el Minar <#ff8d0a>Ancient Debris.<reset>"

    version_header: ""
    version_plugin_info: "<gold><bold><plugin_name></bold> <gray>v<plugin_version></gray>"
    version_author_info: "<yellow>Autor: <white><plugin_authors>"
    version_footer: ""
